// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDocs3-T4LMYdPtqkVWIcFMXMYtW3R-4Ok',
    appId: '1:789322641949:android:0f3480febbfbdd283c0cf4',
    messagingSenderId: '789322641949',
    projectId: 'we-chat-c84be',
    storageBucket: 'we-chat-c84be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGjDw_R7QMQ-8dhp-pfZ4jaxmNaVhZ4YY',
    appId: '1:789322641949:ios:e3acd16731c82fa43c0cf4',
    messagingSenderId: '789322641949',
    projectId: 'we-chat-c84be',
    storageBucket: 'we-chat-c84be.appspot.com',
    androidClientId: '789322641949-n4rs7nn9lhollpl2n57k3jaf00c8g5as.apps.googleusercontent.com',
    iosClientId: '789322641949-j56v2sjp7ihecjhfgnn8jjr79qm84ike.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
